name: update-memos

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0,6,12,18,21 * * *"
  workflow_dispatch:

env:
  GITHUB_NAME: ${{ secrets.GH_NAME }} # 你的github昵称
  GITHUB_EMAIL: ${{ secrets.GH_EMAIL }} # 你的github邮箱
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # github token

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@latest
      with:
        go-version: '>=1.20'
        check-latest: true

    - name: Update Memos #Memos更新
      run: |
        git clone https://github.com/usememos/memos.git
        cd memos
        go build -o memos ./main.go

    - name: Push Memos # 最新版Memos上传
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update memos"
        files: memos
        rebase: 'true'
        name: ${{ env.GITHUB_NAME }}
        email: ${{ env.GITHUB_EMAIL }}
